### PR TITLE
On shutdown: give up HA handover after 3s, not 5m

### LINKED ISSUE #350: Icinga DB does not exit when reconnecting to the database
At exit, Icinga DB will remove its instance from the database. This is done with an unbound ctx which will try to reconnect for 5 minutes even if Icinga DB was requested to shut down.

# Steps to reproduce

- Stop database service.
- Interrupt or kill Icinga DB.

### PR DESCRIPTION
**Pull request by Al2Klimov**
... not to hang for 5m if DB is down.

fixes #350

### CODE REVIEW

**Comment by Al2Klimov** [comment]
## Before

```
2021-09-22T12:42:07.764+0200  INFO    icingadb/main.go:247    Exiting due to signal   {"signal": "interrupt"}
2021-09-22T12:42:07.765+0200    DEBUG   icingadb/ha.go:263      Removing our row from icingadb_instance {"instance_id": "bbfdb09c922e464cbbffa512d4dc7855"}
...
2021-09-22T12:47:07.765+0200    WARN    icingadb/ha.go:268      Could not remove instance from database {"error": "can't connect to database: can't retry: dial tcp 127.0.0.1:6033: connect: connection refused", "errorVerbose": ...
```

## After

```
2021-09-22T13:02:42.571+0200  INFO    icingadb/main.go:256    Exiting due to signal   {"signal": "interrupt"}
...
2021-09-22T13:02:42.572+0200    DEBUG   icingadb/ha.go:263      Removing our row from icingadb_instance {"instance_id": "777acaa97e424f789c63c62107f7c429"}
...
2021-09-22T13:02:45.577+0200    WARN    icingadb/ha.go:268      Could not remove instance from database {"error": "can't connect to database: can't retry: dial tcp 127.0.0.1:6033: connect: connection refused", "errorVerbose": ...
```

File: cmd/icingadb/main.go [hunk 1]
```diff
@@ -67,9 +68,17 @@ func run() int {
...
 	// Closing ha on exit ensures that this instance retracts its heartbeat
 	// from the database so that another instance can take over immediately.
-	defer ha.Close()
+	{
+		defer func() {
+			ctx, cancelCtx := context.WithTimeout(context.Background(), 3*time.Second)
+			ha.Close(ctx)
+			cancelCtx()
+		}()
+	}
```
Comment (julianbrost) [inline cmd/icingadb/main.go:80]: What's the point of these curly braces? That defer statement won't pollute the surrounding scope with any names or something like that.

File: cmd/icingadb/main.go [hunk 2]
```diff
@@ -67,9 +68,17 @@ func run() int {
 
 	heartbeat := icingaredis.NewHeartbeat(ctx, rc, logger)
 	ha := icingadb.NewHA(ctx, db, heartbeat, logger)
+
 	// Closing ha on exit ensures that this instance retracts its heartbeat
 	// from the database so that another instance can take over immediately.
-	defer ha.Close()
+	{
+		defer func() {
+			ctx, cancelCtx := context.WithTimeout(context.Background(), 3*time.Second)
```
Comment (julianbrost) [inline cmd/icingadb/main.go:76]: Were 3 seconds chosen arbitrarily or is there some reasoning behind it (i.e. gives time for a certain number of retries or something like that)?

File: pkg/icingadb/ha.go [hunk 3]
```diff
@@ -259,11 +259,11 @@ func (h *HA) realize(s *icingaredisv1.IcingaStatus, t *types.UnixMilli, shouldLo
 	return nil
 }
 
-func (h *HA) removeInstance() {
+func (h *HA) removeInstance(ctx context.Context) {
 	h.logger.Debugw("Removing our row from icingadb_instance", zap.String("instance_id", hex.EncodeToString(h.instanceId)))
 	// Intentionally not using a context here as this is a cleanup task and h.ctx is already cancelled.
```
Comment (julianbrost) [inline pkg/icingadb/ha.go:264]: That comment is now outdated as some context is used now. IMHO it would also be fine to just create the context with timeout right here.

**Review by julianbrost — CHANGES_REQUESTED** [review]

File: cmd/icingadb/main.go (hunk 1 above)
Comment (Al2Klimov) [reply cmd/icingadb/main.go]: That was an 🐘.

File: cmd/icingadb/main.go (hunk 2 above)
Comment (Al2Klimov) [reply cmd/icingadb/main.go]: Arbitrarily.

**Review by julianbrost — APPROVED** [review]
I find it a bit strange to pass through a context all the way to implement a timeout (maybe someone can give a second opinion on that), but does the job, so fine for me I guess.

**Comment by Al2Klimov** [comment]
Errm... that's one of its main purposes?

**Comment by julianbrost** [comment]
Yes, but for this you don't have to pass it through all the functions but could also create it right within `removeInstance()`.

File: cmd/icingadb/main.go [hunk 4]
```diff
@@ -67,9 +68,15 @@ func run() int {
 
 	heartbeat := icingaredis.NewHeartbeat(ctx, rc, logger)
 	ha := icingadb.NewHA(ctx, db, heartbeat, logger)
+
 	// Closing ha on exit ensures that this instance retracts its heartbeat
 	// from the database so that another instance can take over immediately.
-	defer ha.Close()
+	defer func() {
+		ctx, cancelCtx := context.WithTimeout(context.Background(), 3*time.Second)
```
Comment (lippserd) [inline cmd/icingadb/main.go:75]: I'd like to see a comment, why we have a timeout here.

**Review by lippserd — CHANGES_REQUESTED** [review]
I'd like to see a comment somewhere why we're having ctx with a timeout here.

**Review by lippserd — APPROVED** [review]
