### PR TITLE
Abort HA Realization Logic After Timeout

### LINKED ISSUE #787: Competing HA takeover results in both instances becoming active
## Describe the bug

Apparently there is a race condition in our HA realize handlings that can occur from time to time, causing both Icinga DB instances to become active/responsible at the same time. It is possible for the following to happen if both instances access the `icingadb_instance` table at the same time.

Since both instances are trying to update that table quite often[^1], it is to be expected that they will deadlock each other, as can be seen in the logs.
```json
{
    "_SOURCE_REALTIME_TIMESTAMP": "2024-07-25 11:57:43",
    "MESSAGE": "high-availability: Can't update or insert instance. Retrying",
    "ICINGADB_ERROR": "can't perform \"INSERT INTO \\\"icingadb_instance\\\"...: Error 1213 (40001): Deadlock found when trying to get lock; try restarting transaction"
}
```

However, this retry mechanism also prevents new heartbeat events from being consumed from the channel and results in such weird situation.
```json
{
    "_SOURCE_REALTIME_TIMESTAMP": "2024-07-25 11:57:41",
    "ICINGADB_PREVIOUS": "2024-07-25 11:57:38.433795293 +0200 CEST",
    "ICINGADB_CURRENT": "2024-07-25 11:57:41.433328734 +0200 CEST",
    "MESSAGE": "heartbeat: Previous heartbeat not read from channel",
}
```

In order to prevent it from being retried endlessly, though, we have a deadline[^2] for the entire HA realize thing.
https://github.com/Icinga/icingadb/blob/f9ce7a57bcb6a5b6b2ebfafafd8f91367e56bbf5/pkg/icingadb/ha.go#L220-L221

Unfortunately, if all this retry error mess then lasts for exactly one minute, and barely manages to survive the context deadline, it becomes in the end a wasted time, as after this delay the heartbeat of a given instance is already outdated, but has nevertheless been written to the database. Obviously, the current instance remains responsible, it just has written an outdated heartbeat timestamp to the database because of the deadlocks. When the passive instance finally reads that timestamp, it thinks that the other instance is no longer available and takes over the HA responsibility.
https://github.com/Icinga/icingadb/blob/f9ce7a57bcb6a5b6b2ebfafafd8f91367e56bbf5/pkg/icingadb/ha.go#L319-L321

Having two active instances, however, does not produce any good results and brings down one of the two services.

<details><summary>Active IcingaDB Instance</summary>

```json
{
    "_SOURCE_REALTIME_TIMESTAMP": "2024-07-25 11:58:32",
    "ICINGADB_PREVIOUS": "2024-07-25 11:58:29.433879058 +0200 CEST",
    "ICINGADB_CURRENT": "2024-07-25 11:58:32.433682676 +0200 CEST",
    "MESSAGE": "heartbeat: Previous heartbeat not read from channel",
},
{
    "_SOURCE_REALTIME_TIMESTAMP": "2024-07-25 11:58:35",
    "ICINGADB_PREVIOUS": "2024-07-25 11:58:32.433682676 +0200 CEST",
    "ICINGADB_CURRENT": "2024-07-25 11:58:35.433895608 +0200 CEST",
    "MESSAGE": "heartbeat: Previous heartbeat not read from channel",
},
{
    "_SOURCE_REALTIME_TIMESTAMP": "2024-07-25 11:58:38",
    "ICINGADB_PREVIOUS": "2024-07-25 11:58:35.433895608 +0200 CEST",
    "ICINGADB_CURRENT": "2024-07-25 11:58:38.432917241 +0200 CEST",
    "MESSAGE": "heartbeat: Previous heartbeat not read from channel",
},
{
    "_SOURCE_REALTIME_TIMESTAMP": "2024-07-25 11:58:41",
    "MESSAGE": "high-availability: Instance updated/inserted successfully after error",
    "ICINGADB_AFTER": "1m9.144891965s",
    "ICINGADB_RECOVERED_ERROR": "can't perform \"INSERT INTO \\\"icingadb_instance\\\"...: Error 1213 (40001): Deadlock found when trying to get lock; try restarting transaction",
}
```

Take a closer look at the `ICINGADB_AFTER` field of the above log entry `"ICINGADB_AFTER": "1m9.144891965s"` originated from this part of the code.
https://github.com/Icinga/icingadb/blob/f9ce7a57bcb6a5b6b2ebfafafd8f91367e56bbf5/pkg/icingadb/ha.go#L410-L413

The other(passive) Instance uses the heartbeat timestamp of this Instance from the database to determine that this currently active Instance is absent, by verifying that our timestamp does not exceed the `1m` + grace period of **5s** limit. However, this instance has spent over a minute and 5 seconds (to be precise, it took `1m9.144891965s`) to record the heartbeat, so that it immediately exceeded the aforementioned limit right after the upsert.
https://github.com/Icinga/icingadb/blob/f9ce7a57bcb6a5b6b2ebfafafd8f91367e56bbf5/pkg/icingadb/ha.go#L319 https://github.com/Icinga/icingadb/blob/f9ce7a57bcb6a5b6b2ebfafafd8f91367e56bbf5/pkg/icingadb/ha.go#L25-L28

Subsequently, the other Instance takes over the HA responsibility, even though this one is actually still responsible.

</details> 

<details><summary>Passive IcingaDB Instance</summary>

```json
{
    "_SOURCE_REALTIME_TIMESTAMP": "2024-07-25 11:58:33",
    "MESSAGE": "high-availability: Can't update or insert instance. Retrying",
    "ICINGADB_ERROR": "can't commit transaction: Error 1213 (40001): Deadlock found when trying to get lock; try restarting transaction"
},
{
    "_SOURCE_REALTIME_TIMESTAMP": "2024-07-25 11:58:41",
    "ICINGADB_PREVIOUS": "2024-07-25 11:58:38.302404535 +0200 CEST",
    "ICINGADB_CURRENT": "2024-07-25 11:58:41.299007643 +0200 CEST",
    "MESSAGE": "heartbeat: Previous heartbeat not read from channel",
},
{
    "_SOURCE_REALTIME_TIMESTAMP": "2024-07-25 11:58:43",
    "ICINGADB_HEARTBEAT": "2024-07-25 11:57:32.259000062 +0200 CEST",
    "ICINGADB_HEARTBEAT_AGE": "1m11.394978989s",
    "MESSAGE": "high-availability: Preparing to take over HA as other instance's heartbeat has expired",
},
{
    "_SOURCE_REALTIME_TIMESTAMP": "2024-07-25 11:58:44",
    "ICINGADB_PREVIOUS": "2024-07-25 11:58:41.299007643 +0200 CEST",
    "ICINGADB_CURRENT": "2024-07-25 11:58:44.298509894 +0200 CEST",
    "MESSAGE": "heartbeat: Previous heartbeat not read from channel",
},
{
    "_SOURCE_REALTIME_TIMESTAMP": "2024-07-25 11:59:15",
    "MESSAGE": "high-availability: Instance updated/inserted successfully after error",
    "ICINGADB_AFTER": "1m3.721497393s",
    "ICINGADB_RECOVERED_ERROR": "can't commit transaction: Error 1213 (40001): Deadlock found when trying to get lock; try restarting transaction",
},
```

Afterwards, the passive instance also becomes active and starts its initial config sync and encounters numerous duplicate key and deadlock errors until one of the queries exceeds the retry limit of `5m` and crashes the Icinga DB process.

```json
{
    "_SOURCE_REALTIME_TIMESTAMP": "2024-07-25 11:59:20",
    "MESSAGE": "dump-signals: Received dump signal from Redis",
},
{
    "_SOURCE_REALTIME_TIMESTAMP": "2024-07-25 12:00:20",
    "MESSAGE": "database: Can't execute query. Retrying",
    "ICINGADB_ERROR": "can't perform \"INSERT INTO \\\"host_customvar\\\"...: Error 1062 (23000): Duplicate entry '\\xDE\\xF7i\\xF9\\x9A\\xFEz\\xF6\\x8B\\x107\\xAAE\\xF0\\xBE\\xFF\\xA1Z\\xD3...' for key 'PRIMARY'"
},
{
    "_SOURCE_REALTIME_TIMESTAMP": "2024-07-25 12:00:20",
    "MESSAGE": "database: Can't execute query. Retrying",
    "ICINGADB_ERROR": "can't perform \"INSERT INTO \\\"notification_customvar\\\"...: Error 1062 (23000): Duplicate entry '~\\x1E\\xEB\\x8B\\x8D\\xC2g\\x07\\xE4\\x8A\\xA0^\\x13\\x14\\xE0l\\xD0\\x0F\\...' for key 'PRIMARY'"
},
{
    "_SOURCE_REALTIME_TIMESTAMP": "2024-07-25 12:00:20",
    "MESSAGE": "database: Can't execute query. Retrying",
    "ICINGADB_ERROR": "can't perform \"INSERT INTO \\\"state_history\\\"...: Error 1213 (40001): Deadlock found when trying to get lock; try restarting transaction"
},
{
    "_SOURCE_REALTIME_TIMESTAMP": "2024-07-25 12:00:20",
    "MESSAGE": "database: Query retried successfully after error",
    "ICINGADB_AFTER": "833.661486ms",
    "ICINGADB_RECOVERED_ERROR": "can't perform \"INSERT INTO \\\"state_history\\\"...: Error 1213 (40001): Deadlock found when trying to get lock; try restarting transaction",
},
{
    "_SOURCE_REALTIME_TIMESTAMP": "2024-07-25 12:04:22",
    "MESSAGE": "Error 1062 (23000): Duplicate entry '\\xE9\\xF6\\xC3\\x12\\xA1\\xBE\\xBCo8`h\\xBCA3\\xD72rED\\xE0' for key 'PRIMARY'\ncan't perform \"INSERT INTO \\\"host_customvar\\\" (\\\"host_id\\\", \\\"customvar_id\\\", \\\"environment_id\\\", \\\"id\\\") VALUES (:host_id, :customvar_id, :environment_id, :id)\"\ngithub.com/icinga/icingadb/internal.CantPerformQuery\n\tgithub.com/icinga/icingadb/internal/internal.go:30\ngithub.com/icinga/icingadb/pkg/icingadb.(*DB).NamedBulkExec.func1.(*DB).NamedBulkExec.func1.1.2.1\n\tgithub.com/icinga/icingadb/pkg/icingadb/db.go:412\ngithub.com/icinga/icingadb/pkg/retry.WithBackoff\n\tgithub.com/icinga/icingadb/pkg/retry/retry.go:60\ngithub.com/icinga/icingadb/pkg/icingadb.(*DB).NamedBulkExec.func1.(*DB).NamedBulkExec.func1.1.2\n\tgithub.com/icinga/icingadb/pkg/icingadb/db.go:407\ngolang.org/x/sync/errgroup.(*Group).Go.func1\n\tgolang.org/x/sync@v0.7.0/errgroup/errgroup.go:78\nruntime.goexit\n\truntime/asm_amd64.s:1695\nretry deadline exceeded\ngithub.com/icinga/icingadb/pkg/retry.WithBackoff\n\tgithub.com/icinga/icingadb/pkg/retry/retry.go:95\ngithub.com/icinga/icingadb/pkg/icingadb.(*DB).NamedBulkExec.func1.(*DB).NamedBulkExec.func1.1.2\n\tgithub.com/icinga/icingadb/pkg/icingadb/db.go:407\ngolang.org/x/sync/errgroup.(*Group).Go.func1\n\tgolang.org/x/sync@v0.7.0/errgroup/errgroup.go:78\nruntime.goexit\n\truntime/asm_amd64.s:1695",
}
```

</details> 

ref/IP/48748

## Additional context

```bash
Error 1062 (23000): Duplicate entry '\\xE9\\xF6\\xC3\\x12\\xA1\\xBE\\xBCo8`h\\xBCA3\\xD72rED\\xE0' for key 'PRIMARY'
can't perform \"INSERT INTO \"host_customvar\" (\"host_id\", \"customvar_id\", \"environment_id\", \"id\") VALUES (:host_id, :customvar_id, :environment_id, :id)\"
github.com/icinga/icingadb/internal.CantPerformQuery
    github.com/icinga/icingadb/internal/internal.go:30
github.com/icinga/icingadb/pkg/icingadb.(*DB).NamedBulkExec.func1.(*DB).NamedBulkExec.func1.1.2.1
    github.com/icinga/icingadb/pkg/icingadb/db.go:412
github.com/icinga/icingadb/pkg/retry.WithBackoff
    github.com/icinga/icingadb/pkg/retry/retry.go:60
github.com/icinga/icingadb/pkg/icingadb.(*DB).NamedBulkExec.func1.(*DB).NamedBulkExec.func1.1.2
    github.com/icinga/icingadb/pkg/icingadb/db.go:407
golang.org/x/sync/errgroup.(*Group).Go.func1
    golang.org/x/sync@v0.7.0/errgroup/errgroup.go:78
runtime.goexit
    runtime/asm_amd64.s:1695
retry deadline exceeded
github.com/icinga/icingadb/pkg/retry.WithBackoff
    github.com/icinga/icingadb/pkg/retry/retry.go:95
github.com/icinga/icingadb/pkg/icingadb.(*DB).NamedBulkExec.func1.(*DB).NamedBulkExec.func1.1.2
    github.com/icinga/icingadb/pkg/icingadb/db.go:407
golang.org/x/sync/errgroup.(*Group).Go.func1
    golang.org/x/sync@v0.7.0/errgroup/errgroup.go:78
runtime.goexit
    runtime/asm_amd64.s:1695
```

[^1]:  It's a well-known fact that the Icinga 2 heartbeats arrives in Redis every 1 second, but we only read them every `3` seconds and these 3 seconds are the pacesetter for HA realize thing.
[^2]: The overall Redis heartbeat timeout is set to `1m`, i.e. if we do not receive an Icinga 2 heartbeat for more than one minute, we hand over the HA responsibility. Seemingly, that very same timeout is also used as a deadline for the HA transaction retry's.

### PR DESCRIPTION
**Pull request by oxzi**
- **icingadb: Unify select cases for derived contexts**
  The main loop select cases for hactx.Done() and ctx.Done() were unified, as hactx is a derived ctx. A closed ctx case may be lost as the hactx case could have been chosen.
- **HA: Increase log level for heartbeats from the future**
  Timing issues may be the root of future failures. Thus, it is important to be aware if the timing seems to be out of sync.
- **HA: Deferred SQL Transaction Rollback**
  Each transaction is created within the retryable function, but this function may be exited prematurely before committing. A deferred rollback ensures that the transaction will be rolled back and cleaned up in this case, or will be a noop when performed after the commit.
- **HA: Insert environment within retryable function**
  The HA.insertEnvironment() method was inlined into the retryable function to use the deadlined context. Otherwise, this might block afterwards, as it was used within HA.realize(), but without the passed context.
- **HA/Heartbeat: Use last message's timestamp**
  Since the retryable HA function may be executed a few times before succeeding, the inserted heartbeat value will be directly outdated. The heartbeat logic was slightly altered to always use the latest heartbeat time value.
- **HA: Abort Transaction Commit after Timeout**
  A strange HA behavior was reported in #787, resulting in both instances being active.
  The logs contained an entry of the previous active instance exiting the HA.realize() method successfully after 1m9s. This, however, should not be possible as the method's context is deadlined to a minute after the heartbeat was received.
  However, as it turns out, executing COMMIT on a database transaction is not bound to the transaction's context, allowing to survive longer. To mitigate this, another context watch was introduced. Doing so allows directly handing over, while the other instance can now take over due to the expired heartbeat in the database.

Closes #787.

### CODE REVIEW

File: pkg/icingadb/ha.go [hunk 1]
```diff
@@ -264,6 +264,9 @@ func (h *HA) controller() {
 
 // realize a HA cycle triggered by a heartbeat event.
 //
+// The given context MUST have a deadline, as the method will otherwise panic. This deadline is hardly enforced to
+// cancel the logic if it has expired.
```
Comment (julianbrost) [inline pkg/icingadb/ha.go:268]: Hint: look up the meaning of "hardly", this sounds like it's not what you'd expect :sweat_smile:

Comment (oxzi) [reply pkg/icingadb/ha.go:268]: A hard working person or a hardly working person. There was a difference, I remember. Oops.

**Comment by oxzi** [comment]
After going over this with @lippserd, I reworked this PR. The changes are, in a nutshell, that the potentially blocking `COMMIT` query will be guarded with a `select` watching at the context and that always the latest heartbeat timestamp will be used, as otherwise an already heartbeat will be retried. The description in the initial post was updated accordingly.

File: pkg/icingadb/ha.go [hunk 2]
```diff
@@ -370,23 +376,48 @@ func (h *HA) realize(
...
+				return ctx.Err()
 			}
 
 			return nil
 		},
 		retry.Retryable,
 		backoff.NewExponentialWithJitter(256*time.Millisecond, 3*time.Second),
 		retry.Settings{
-			// Intentionally no timeout is set, as we use a context with a deadline.
+			// Intentionally, no timeout is set because a context with a deadline is used and QuickContextExit is set.
```
Comment (lippserd) [inline pkg/icingadb/ha.go:420]: QuickContextExit is no longer there ;).

File: pkg/icingadb/ha.go [hunk 3]
```diff
@@ -370,23 +376,48 @@ func (h *HA) realize(
...
+			// context support to sql: https://github.com/golang/go/issues/15123#issuecomment-245882486
+			//
+			// The following is implementation knowledge, not covered by the API specification. Go's sql.Tx.Commit() -
+			// which is not being overridden by sqlx.Tx - performs a preflight check on the context before handing over
+			// to the driver's Commit method. The drivers may behave differently. For example, the used
+			// github.com/go-sql-driver/mysql package calls its internal exec method with a "COMMIT" query, writing and
+			// reading packets without honoring the context.
+			//
+			// In a nutshell, one cannot expect a Commit() call to be covered by the transaction context. Thus, an
+			// additional check wraps the call, ensuring that this function will be left when the context is done.
```
Comment (lippserd) [inline pkg/icingadb/ha.go:402]: Can you please also add a comment that it is theoretically no problem to call realize again while the COMMIT is still running in the go routine.

**Review by lippserd — CHANGES_REQUESTED** [review]
Please rebase and add a comment about `COMMIT` possibly not respecting context deadlines in `ExecTx()` and `NamedExecTx()`.

File: pkg/icingadb/ha.go (hunk 3 above)
Comment (oxzi) [reply pkg/icingadb/ha.go]: I wrote more prose. Please take another look.

**Review by lippserd — APPROVED** [review]

File: pkg/icingadb/ha.go (hunk 3 above)
Comment (lippserd) [reply pkg/icingadb/ha.go]: Looks good, ty! 👍

File: pkg/icingaredis/heartbeat.go [hunk 4]
```diff
@@ -25,6 +25,7 @@ type Heartbeat struct {
 	active         bool
 	events         chan *HeartbeatMessage
 	lastReceivedMs int64
+	lastMessageMs  int64
```
Comment (yhabteab) [inline pkg/icingaredis/heartbeat.go:28]: Am I missing something? Why can't you make this of type `atomic.Int64` and use its `Load()` and `Store()` methods?

File: pkg/icingaredis/heartbeat.go [hunk 5]
```diff
@@ -62,6 +63,11 @@ func (h *Heartbeat) LastReceived() int64 {
 	return atomic.LoadInt64(&h.lastReceivedMs)
 }
 
+// LastMessage returns the last message's time in ms.
+func (h *Heartbeat) LastMessage() int64 {
```
Comment (yhabteab) [inline pkg/icingaredis/heartbeat.go:67]: Since this does not return the actual heartbeat message, it should be named according to what it actually returns.

File: pkg/icingaredis/heartbeat.go (hunk 4 above)
Comment (oxzi) [reply pkg/icingaredis/heartbeat.go:28]: It was implemented this way to be symmetrical to `lastReceivedMs`, especially in the later calls.

Comment (yhabteab) [reply pkg/icingaredis/heartbeat.go:28]: The previous implementation was designed that way because `atomic.Int64` was not available prior to [Go 1.19](https://go.dev/doc/go1.19#atomic_types).

File: pkg/icingaredis/heartbeat.go (hunk 5 above)
Comment (oxzi) [reply pkg/icingaredis/heartbeat.go:67]: This method name tries to follow `LastReceived`, returning the last received timestamp while `LastMessage` returns the last message's timestamp. Thus, what would you suggest then? Especially when fitting with its twin method.

File: pkg/icingaredis/heartbeat.go (hunk 4 above)
Comment (oxzi) [reply pkg/icingaredis/heartbeat.go:28]: Okay, but it works, right? There is no necessity to change it, which would blow up this change, btw. And having these two implemented differently would just look odd.

Comment (yhabteab) [reply pkg/icingaredis/heartbeat.go:28]: > There is no necessity to change it, which would blow up this change, btw. And having these two implemented differently would just look odd.

I was referring to the new type you introduced and did not mean for you to change the existing code. Personally, we should be more focused on using new features rather than maintaining symmetry with the existing code :), anyway I've changed the existing usages with #829.

File: pkg/icingaredis/heartbeat.go (hunk 5 above)
Comment (yhabteab) [reply pkg/icingaredis/heartbeat.go:67]: > while `LastMessage` returns the last message's timestamp. Thus, what would you suggest then?

Please don't take this the wrong way, and I'm not trying to impose my own ideals on you. I just think that `LastMessage` is not the same as `last message timestamp`, and I apologize for not providing an alternative name from the beginning that I'm thinking of. Thus, my first suggestion would be to simply call it `LastMessageTime[stamp]`.

File: pkg/icingaredis/heartbeat.go (hunk 4 above)
Comment (oxzi) [reply pkg/icingaredis/heartbeat.go:28]: Personally, I don't think always using the latest features is something to strive for, unless it adds real value. In that case, the API is more foolproof. I am for changing it, as you did, but then it should be done consequentially. I will update this PR as well.

**Review by yhabteab — COMMENTED** [review]
Apart from the conflict, everything looks fine to me now. Sorry for that :)

**Review by lippserd — CHANGES_REQUESTED** [review]
Although I approved earlier, I now have something that I had previously forgotten. It's not about the code itself, but about the commit(s). The changes here are subject to multiple commits:

* Changes in main
* Increasing the "heartbeat from future" log to warning
* Explicit rollback
* Inserting the environment inside the transaction
* Introduction and use of LastMessageTime() (plus the corresponding godoc paragraph of realize)
* Executing commit in a separate Go routine (plus its godoc paragraph of realize)

**Review by lippserd — APPROVED** [review]
Perfect, thanks a lot @oxzi!

**Review by yhabteab — APPROVED** [review]

**Comment by yhabteab** [comment]
Shouldn't this pull request close issue #787?

**Comment by oxzi** [comment]
> Shouldn't this pull request close issue #787?

This was the initial motivation, yes. However, as I was unable to reproduce the reported behavior, I cannot verify this. My intention was to make the observed bug impossible with this change, but maybe there is still another bug lurking around the corner.

However, with a bit more trust in this change, I have linked this PR to the issue. Otherwise, we can reopen it.
