### PR TITLE
Dedicated SQL Connection For Schema Import

### LINKED ISSUE #1002: --database-auto-import causes SQL syntax error on first start
## To Reproduce

1. `apt install icinga2 icingadb-redis icingadb mariadb-server`
2. `icinga2 api setup`
3. `sed 's/^/#/' -i /etc/icinga2/icinga2.conf`
4. `sed '1i object JournaldLogger "mainlog" { }' -i /etc/icinga2/icinga2.conf`
5. `sed '2i object IcingaDB "icingadb" { }' -i /etc/icinga2/icinga2.conf`
6. `systemctl reload icinga2.service`
7. https://icinga.com/docs/icinga-db/latest/doc/02-Installation/Debian/#setting-up-a-mysql-or-mariadb-database
8. `sed 's/^/#/' -i /etc/icingadb/config.yml`
9. `sed '1i {"database":{"host":"/run/mysqld/mysqld.sock","user":"icingadb","password":"CHANGEME","database":"icingadb"},"redis":{"host":"127.0.0.1"}}' -i /etc/icingadb/config.yml`
10. `systemctl restart icingadb`
11. `systemctl status icingadb` # 👍 works
12. `systemctl stop icingadb`
13. `DROP DATABASE icingadb;`
14. `CREATE DATABASE icingadb;`
15. `systemctl edit icingadb` # see below
16. `systemctl start icingadb`
17. `systemctl status icingadb` # 👎 broken, see below

### `systemctl edit icingadb`

```
[Service]
ExecStart=
ExecStart=/usr/sbin/icingadb --config /etc/icingadb/config.yml --database-auto-import --database-schema-dir=/usr/share/icingadb/schema
```

## Describe the bug

```
× icingadb.service - Icinga DB
     Loaded: loaded (/lib/systemd/system/icingadb.service; enabled; preset: enabled)
    Drop-In: /etc/systemd/system/icingadb.service.d
             └─override.conf
     Active: failed (Result: exit-code) since Wed 2025-08-06 09:59:17 UTC; 57s ago
   Duration: 1.689s
    Process: 4714 ExecStart=/usr/sbin/icingadb --config /etc/icingadb/config.yml --database-auto-import --database-schema-dir=/usr/share/icingadb/schema (code=exited, status=1/FAILURE)
   Main PID: 4714 (code=exited, status=1/FAILURE)
        CPU: 38ms

Aug 06 09:59:16 ak-synerr icingadb[4714]: heartbeat: Received Icinga heartbeat
Aug 06 09:59:16 ak-synerr icingadb[4714]: Taking over
Aug 06 09:59:16 ak-synerr icingadb[4714]: Starting config sync
Aug 06 09:59:16 ak-synerr icingadb[4714]: Starting initial state sync
Aug 06 09:59:16 ak-synerr icingadb[4714]: Starting overdue sync
Aug 06 09:59:16 ak-synerr icingadb[4714]: config-sync: Aborted initial state sync after 9.740887ms
Aug 06 09:59:16 ak-synerr icingadb[4714]: config-sync: Aborted config sync after 10.348706ms
Aug 06 09:59:17 ak-synerr icingadb[4714]: Error 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '"eventcommand_argument" WHERE "environment_id" = ?' at line 1
                                          can't perform "SELECT \"properties_checksum\", \"id\" FROM \"eventcommand_argument\" WHERE \"environment_id\" = :environment_id"
                                          github.com/icinga/icinga-go-library/database.CantPerformQuery
                                                  github.com/icinga/icinga-go-library@v0.7.2/database/utils.go:19
                                          github.com/icinga/icinga-go-library/database.(*DB).YieldAll.func1
                                                  github.com/icinga/icinga-go-library@v0.7.2/database/db.go:666
                                          golang.org/x/sync/errgroup.(*Group).add.func1
                                                  golang.org/x/sync@v0.15.0/errgroup/errgroup.go:128
                                          runtime.goexit
                                                  runtime/asm_amd64.s:1700
Aug 06 09:59:17 ak-synerr systemd[1]: icingadb.service: Main process exited, code=exited, status=1/FAILURE
Aug 06 09:59:17 ak-synerr systemd[1]: icingadb.service: Failed with result 'exit-code'.
```

## Expected behavior

No SQL syntax error.

## Your Environment

Include as many relevant details about the environment you experienced the problem in

* Icinga DB version: 1.4
* Icinga 2 version: 2.15
* Operating System and version: Debian 12

### PR DESCRIPTION
**Pull request by oxzi**
Use a dedicated SQL connection for the schema import to eliminate side effects on future queries.

In particular, the MySQL/MariaDB schema file began by altering SQL system variables, such as "sql_mode". These changes persist throughout the entire connection, affecting every subsequent query.

Our database queries require the ANSI_QUOTES[0] SQL mode. However, the schema file had unset this mode, which resulted in failed queries and a subsequent Icinga DB crash. This was reported independently in #1002 and in the community forum[1].

Creating a short-lived, dedicated SQL connection for the schema import eliminates any impact on the main database connection.

Fixes #1002.

[0]: https://dev.mysql.com/doc/refman/8.4/en/sql-mode.html#sqlmode_ansi_quotes
[1]: https://community.icinga.com/t/error-1064-42000-you-have-an-error-in-your-sql-syntax-on-initialization/15080

### CODE REVIEW

**Review by Al2Klimov — APPROVED** [review]
# Setup

## icinga2.conf

```
object JournaldLogger "mainlog" { }

object IcingaDB "icingadb" { }
```

## icingadb.yml

```yaml
database:
  host: /run/mysqld/mysqld.sock
  user: icingadb
  database: icingadb
redis:
  host: 127.0.0.1
```

## icinga2.bash

```bash
set -e
cd /var/lib/icinga2

if ! [ -e ca/ca.crt ]; then
  icinga2 pki new-ca
fi

mkdir -p certs
cp ca/ca.crt certs
```

## import-me.nix

```nix
{ pkgs, ... }:
let
  icingadbSrc = pkgs.fetchFromGitHub {
    owner = "Icinga";
    repo = "icingadb";
    rev = "10d143e33157242e08d979155e111263a2820711";
    hash = "sha256-+aPhOCoWjaJPgs9qwHpwZuzMdr5ResolptwYb4YMEDQ=";
  };
in {
  users.groups.icinga2 = { };

  users.users.icinga2 = {
    isSystemUser = true;
    group = "icinga2";
  };

  systemd.services.icinga2 = with pkgs; {
    serviceConfig = {
      ExecStartPre = "+${bash}/bin/bash ${./icinga2.bash}";
      ExecStart = "+${icinga2.overrideAttrs (_: prev: {
        cmakeFlags = prev.cmakeFlags ++ [ "-DICINGA2_UNITY_BUILD=OFF" ];
        src = fetchFromGitHub {
          owner = "Icinga";
          repo = "icinga2";
          rev = "v2.15.0";
          hash = "sha256-IuK6kD2OBAm7bKtPcMnplwNSGyGUcX3UWiwm8Vry1is=";
        };
      })}/bin/icinga2 daemon --close-stdio -c ${./icinga2.conf}";
      Type = "notify";
      NotifyAccess = "all";
      KillMode = "mixed";

      StateDirectory = "icinga2";
      StateDirectoryMode = "0750";
      RuntimeDirectory = "icinga2";
      RuntimeDirectoryMode = "0750";
      CacheDirectory = "icinga2";
      CacheDirectoryMode = "0750";
      User = "icinga2";
    };
    wantedBy = [ "multi-user.target" ];
    path = [ coreutils icinga2 ];
  };

  services.redis.servers.icingadb = {
    enable = true;
    port = 6380;
  };

  users.groups.icingadb = { };

  users.users.icingadb = {
    isSystemUser = true;
    group = "icingadb";
  };

  systemd.services.icingadb = {
    serviceConfig = {
      ExecStart = "${pkgs.buildGoModule {
        name = "icingadb";
        src = icingadbSrc;
        vendorHash = "sha256-qRm6aOsJo+we7upiL2oE9CiPbm9+xyrHhrKlP9kg894=";
        subPackages = [ "cmd/icingadb" ];
      }}/bin/icingadb -c ${./icingadb.yml} --database-auto-import --database-schema-dir=${icingadbSrc}/schema";
      Type = "notify";
      User = "icingadb";
    };
    wantedBy = [ "multi-user.target" ];
  };

  services.mysql = with pkgs; {
    enable = true;
    package = mariadb;
    initialDatabases = [
      {
        name = "icingadb";
        #schema = "${icingadbSrc}/schema/mysql/schema.sql";
      }
    ];
    ensureUsers = [
      {
        name = "icingadb";
        ensurePermissions."icingadb.*" = "ALL";
      }
    ];
  };
}
```

# Before (10d143e33157242e08d979155e111263a2820711)

```
Aug 20 15:39:37 akidb icingadb[10925]: Error 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '"dependency_node" WHERE "environment_id" = ?' at line 1
                                       can't perform "SELECT \"id\" FROM \"dependency_node\" WHERE \"environment_id\" = :environment_id"
                                       github.com/icinga/icinga-go-library/database.CantPerformQuery
                                               github.com/icinga/icinga-go-library@v0.7.2/database/utils.go:19
                                       github.com/icinga/icinga-go-library/database.(*DB).YieldAll.func1
                                               github.com/icinga/icinga-go-library@v0.7.2/database/db.go:666
                                       golang.org/x/sync/errgroup.(*Group).Go.func1
                                               golang.org/x/sync@v0.16.0/errgroup/errgroup.go:93
                                       runtime.goexit
                                               runtime/asm_amd64.s:1700
Aug 20 15:39:37 akidb systemd[1]: icingadb.service: Main process exited, code=exited, status=1/FAILURE
```

# After (6fd4ad71f44bd2aefe881eaeb36c1a553177b9e4)

```patch
--- import-me.nix
+++ import-me.nix
@@ -6,2 +6,2 @@
-    rev = "10d143e33157242e08d979155e111263a2820711";
-    hash = "sha256-+aPhOCoWjaJPgs9qwHpwZuzMdr5ResolptwYb4YMEDQ=";
+    rev = "6fd4ad71f44bd2aefe881eaeb36c1a553177b9e4";
+    hash = "sha256-u4YOCjHWiS9F4WAHHnMBonTYRuuuywiLNjvSrbEvJ7g=";
```

```
Aug 20 15:50:39 akidb icingadb[17798]: config-sync: Finished config sync in 18.782597ms
```

File: cmd/icingadb/main.go [hunk 1]
```diff
@@ -74,9 +74,19 @@ func run() int {
 		}
 
 		logger.Info("Starting database schema auto import")
+
+		db, err := cmd.Database(logs.GetChildLogger("database"))
+		if err != nil {
+			logger.Fatalw("Can't create database connection pool from config", zap.Error(err))
+		}
+		db.SetMaxOpenConns(1)
```
Comment (Al2Klimov) [inline cmd/icingadb/main.go:82]: And, while on it, I doubt this limit is actually necessary.

Comment (oxzi) [reply cmd/icingadb/main.go:82]: Necessary? No, I don't think so.

However, when this code is executed, the main database connection is also active with its 16 open connections - or whatever the user has configured. Thus, we would have 32 open connection now, which is twice the number of user-configured connections. In addition, importing the schema should be a linear procedure, actually being performed in one database transaction.
