### PR TITLE
schema: Add missing indices to `hostgroup` and `servicegroup`

### LINKED ISSUE #615: Less indexes on `hostgroup` and `servicegroup` than on `usergroup`
## Describe the bug

The tables `hostgroup` and `servicegroup` have no index for `name_ci` and `display_name` while the `usergroup` table has such.

## Expected behavior

All tables should have the same indexes as they are very similar in nature.

### PR DESCRIPTION
**Pull request by nilmerg**
These new indices make these tables consistent with `usergroup`.

fixes #615

### CODE REVIEW

File: schema/mysql/schema.sql [hunk 1]
```diff
@@ -404,7 +406,9 @@ CREATE TABLE servicegroup (
 
   PRIMARY KEY (id),
 
-  INDEX idx_servicegroup_name (name) COMMENT 'Host/service/service group list filtered by service group name'
+  INDEX idx_servicegroup_display_name (display_name) COMMENT 'Servicegroup list filtered/ordered by display_name',
+  INDEX idx_servicegroup_name_ci (name_ci) COMMENT 'Servicegroup list filtered using quick search',
+  INDEX idx_servicegroup_name (name) COMMENT 'Host/service/service group list filtered by service group name; Servicegroup detail filter'
```
Comment (Al2Klimov) [inline schema/mysql/schema.sql:411]: Host list? By service group name? How is this even possible?

**Review by Al2Klimov — COMMENTED** [review]
Fine _in general_, but...

File: schema/mysql/schema.sql (hunk 1 above)
Comment (nilmerg) [reply schema/mysql/schema.sql:411]: Like this:
image
