### PR TITLE
icingadb-migrate: Mitigate NULL names in {comment,downtime}_query

### LINKED ISSUE #766: icingadb-migrate fails with '"name": converting NULL to string is unsupported'
## Describe the bug
Hello,
I'm attempting to migrate a 2015 Icinga installation and I get this error:
```
2024-07-06T04:01:52.802+0200    INFO    icingadb-migrate/main.go:105    Actually migrating
2024-07-06T04:01:52.810+0200    FATAL   icingadb-migrate/misc.go:125    sql: Scan error on column index 10, name "name": converting NULL to string is unsupported
can't perform query
main.sliceIdoHistory[...]
        /var/tmp/portage/net-misc/icingadb-1.2.0/work/icingadb-1.2.0/cmd/icingadb-migrate/misc.go:125
main.migrateOneType[...]
        /var/tmp/portage/net-misc/icingadb-1.2.0/work/icingadb-1.2.0/cmd/icingadb-migrate/main.go:421
main.init.func2
        /var/tmp/portage/net-misc/icingadb-1.2.0/work/icingadb-1.2.0/cmd/icingadb-migrate/misc.go:253
main.migrate.func1
        /var/tmp/portage/net-misc/icingadb-1.2.0/work/icingadb-1.2.0/cmd/icingadb-migrate/main.go:359
main.historyTypes.forEach.func1
        /var/tmp/portage/net-misc/icingadb-1.2.0/work/icingadb-1.2.0/cmd/icingadb-migrate/misc.go:231
golang.org/x/sync/errgroup.(*Group).Go.func1
        /var/tmp/portage/net-misc/icingadb-1.2.0/work/go-mod/golang.org/x/sync@v0.7.0/errgroup/errgroup.go:78
runtime.goexit
        /usr/lib/go/src/runtime/asm_arm64.s:1222        {"query": "SELECT ch.commenthistory_id, UNIX_TIMESTAMP(ch.entry_time) entry_time,\n  ch.entry_time_usec, ch.entry_type, ch.author_name, ch.comment_data, ch.is_persistent,\n  COALESCE(UNIX_TIMESTAMP(ch.expiration_time), 0) expiration_time,\n  COALESCE(UNIX_TIMESTAMP(ch.deletion_time), 0) deletion_time,\n  ch.deletion_time_usec, ch.name, o.objecttype_id, o.name1, COALESCE(o.name2, '') name2\nFROM icinga_commenthistory ch\nINNER JOIN icinga_objects o ON o.object_id=ch.object_id\nWHERE ch.commenthistory_id BETWEEN :fromid AND :toid\nAND ch.commenthistory_id > :checkpoint -- where we were interrupted\nORDER BY ch.commenthistory_id -- this way we know what has already been migrated from just the last row's ID\nLIMIT :bulk\n"}
main.sliceIdoHistory[...]
        /var/tmp/portage/net-misc/icingadb-1.2.0/work/icingadb-1.2.0/cmd/icingadb-migrate/misc.go:125
main.migrateOneType[...]
        /var/tmp/portage/net-misc/icingadb-1.2.0/work/icingadb-1.2.0/cmd/icingadb-migrate/main.go:421
main.init.func2
        /var/tmp/portage/net-misc/icingadb-1.2.0/work/icingadb-1.2.0/cmd/icingadb-migrate/misc.go:253
main.migrate.func1
        /var/tmp/portage/net-misc/icingadb-1.2.0/work/icingadb-1.2.0/cmd/icingadb-migrate/main.go:359
main.historyTypes.forEach.func1
        /var/tmp/portage/net-misc/icingadb-1.2.0/work/icingadb-1.2.0/cmd/icingadb-migrate/misc.go:231
golang.org/x/sync/errgroup.(*Group).Go.func1
        /var/tmp/portage/net-misc/icingadb-1.2.0/work/go-mod/golang.org/x/sync@v0.7.0/errgroup/errgroup.go:78
```

## To Reproduce

I can provide a SQL dump privately if it helps.

## Expected behavior

This should not fail.

## Your Environment

Include as many relevant details about the environment you experienced the problem in

* Icinga DB version: 1.2.0
* Icinga 2 version: 2.14.2
* Operating System and version: Gentoo ~arm64

## Additional context

I noticed that some of my comments have a NULL name and this seems to have stopped occurring between August and December 2015. I probably upgraded something during this time frame.
```
icinga2=# SELECT comment_time FROM icinga_commenthistory WHERE name IS NULL ORDER BY comment_time DESC LIMIT 1;
    comment_time     
---------------------
 2015-08-18 16:29:18
(1 row)

icinga2=# SELECT comment_time FROM icinga_commenthistory WHERE name IS NOT NULL ORDER BY comment_time ASC LIMIT 1;
    comment_time     
---------------------
 2015-12-18 00:39:05
(1 row)
```

### PR DESCRIPTION
**Pull request by oxzi**
Historical data from an older Icinga 2 installation contained NULL values for the name column in some rows of the icinga_commenthistory and icinga_downtimehistory tables.

Normally this field contains something like
${name1}!${name2}!${unique_value} where the $unique_value is based on a timestamp for older entries and a UUID for newer ones. For a concrete example, this could be "host.example.com!ping6!123…".

Unfortunately, using an empty string for these NULL values will cause an error later because the new primary key will be calculated based on it. Therefore, a new deterministic name is generated based on the primary keys and the known name1 and name2 values.

Closes #766.

### CODE REVIEW

File: cmd/icingadb-migrate/embed/comment_query.sql [hunk 1]
```diff
@@ -2,7 +2,9 @@ SELECT ch.commenthistory_id, UNIX_TIMESTAMP(ch.entry_time) entry_time,
   ch.entry_time_usec, ch.entry_type, ch.author_name, ch.comment_data, ch.is_persistent,
   COALESCE(UNIX_TIMESTAMP(ch.expiration_time), 0) expiration_time,
   COALESCE(UNIX_TIMESTAMP(ch.deletion_time), 0) deletion_time,
-  ch.deletion_time_usec, ch.name, o.objecttype_id, o.name1, COALESCE(o.name2, '') name2
+  ch.deletion_time_usec,
+  COALESCE(ch.name, CONCAT(o.name1, '!', COALESCE(o.name2, ''), '!', ch.commenthistory_id, '-', ch.object_id)) name,
```
Comment (Al2Klimov) [inline cmd/icingadb-migrate/embed/comment_query.sql:6]: I assume you made a tradeoff for host comments/downtimes? For such that expression would yield host!!id-id – but this makes the query less complex.

Comment (Al2Klimov) [reply cmd/icingadb-migrate/embed/comment_query.sql:6]: Then what about just ch.commenthistory_id (as fallback)?

Comment (oxzi) [reply cmd/icingadb-migrate/embed/comment_query.sql:6]: I was not certain about the cardinality between `icinga_commenthistory` to `icinga_objects` as `o.name1` and `o.name2` are part of the latter. Thus, I wanted to be sure and have included both `commenthistory_id` and `object_id`.
Furthermore, I liked having a name being similar to the other valid entries, even if it is just being yelled into the void.

Comment (Al2Klimov) [reply cmd/icingadb-migrate/embed/comment_query.sql:6]: Ok, why not.

**Review by Al2Klimov — APPROVED** [review]
