### PR TITLE
Make Database/Redis schema mismatch error more user friendly

### LINKED ISSUE #500: Make early error messages more helpful
The current error messages are hard to understand for users and should give advice on what to do.

For example:
* Unexpected database schema version: *please make sure you have applied all database migrations after upgrading Icinga DB*
* Unexpected Redis schema version: *please make sure you are running compatible versions of Icinga 2 and Icinga DB*

Also, these are more cases where spitting out a stack trace gives no additional information and makes it look more like a bug than a misconfiguration.

### PR DESCRIPTION
**Pull request by yhabteab**
fixes #500

### CODE REVIEW

File: cmd/icingadb/main.go [hunk 1]
```diff
@@ -358,7 +358,10 @@ func checkDbSchema(ctx context.Context, db *icingadb.DB) error {
 	}
 
 	if version != expectedDbSchemaVersion {
-		return errors.Errorf("expected database schema v%d, got v%d", expectedDbSchemaVersion, version)
+		return errors.Errorf(
+			"Unexpected database schema version: v%d (expected v%d). Please make sure you have applied all database"+
+				"migrations after upgrading Icinga DB", version, expectedDbSchemaVersion,
```
Comment (julianbrost) [inline cmd/icingadb/main.go:363]: The resulting message misses a space (same thing with the other message below).

**Review by julianbrost — CHANGES_REQUESTED** [review]
Also, looks like this PR changes nothing about the second thing I suggested in #500:
> Also, these are more cases where spitting out a stack trace gives no additional information and makes it look more like a bug than a misconfiguration.

File: cmd/icingadb/main.go [hunk 2]
```diff
@@ -63,7 +66,9 @@ func run() int {
 	}
 	defer db.Close()
 	{
-		logger.Info("Connecting to database")
+		logger.Infof("Connecting to database at host '%s'", net.JoinHostPort(
+			cmd.Config.Database.Host, strconv.FormatInt(int64(cmd.Config.Database.Port), 10)),
```
Comment (julianbrost) [inline cmd/icingadb/main.go:70]: `fmt.Sprint(cmd.Config.Database.Port)` would do the same here but is shorter/easier to read.

File: cmd/icingadb/main.go [hunk 3]
```diff
@@ -79,7 +84,9 @@ func run() int {
 		logger.Fatalf("%+v", errors.Wrap(err, "can't create Redis client from config"))
 	}
 	{
-		logger.Info("Connecting to Redis")
+		logger.Infof("Connecting to Redis at host '%s'", net.JoinHostPort(
+			cmd.Config.Redis.Host, strconv.FormatInt(int64(cmd.Config.Redis.Port), 10)),
+		)
```
Comment (julianbrost) [inline cmd/icingadb/main.go:89]: Same two comments apply here just as well.

File: cmd/icingadb/main.go [hunk 4]
```diff
@@ -379,9 +392,11 @@ func monitorRedisSchema(logger *logging.Logger, rc *icingaredis.Client, pos stri
 // checkRedisSchema verifies rc's icinga:schema version.
 func checkRedisSchema(logger *logging.Logger, rc *icingaredis.Client, pos string) (newPos string, err error) {
 	if pos == "0-0" {
-		defer time.AfterFunc(3*time.Second, func() { logger.Info("Waiting for current Redis schema version") }).Stop()
+		defer time.AfterFunc(3*time.Second, func() {
+			logger.Info("Waiting for Icinga 2 to write into Redis. Please make sure you have started Icinga 2 and Icinga DB feature is enabled")
```
Comment (julianbrost) [inline cmd/icingadb/main.go:396]: "[...] and **the** Icinga DB feature [...]"

Additionally, I'd either end both sentences with a period here, or just do the same ", please" as with the other messages.

**Review by julianbrost — APPROVED** [review]
